name: Tests for Social Media App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  app_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
