name: Tests for Social Media App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  app_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update and Install Composer Dependencies
        run: composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install npm dependencies
        run: npm install && npm run dev

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory permission
        run: chmod -R 777 storage bootstrap/cache

      # - name: Create Database
      #   run: |
      #     mkdir -p database
      #     touch database/database.sqlite

      # - name: Execute unit and feature test for PHP
      #   env:
      #     DB_CONNECTION: sqlite
      #     DB_DATABASE: database/database.sqlite
      #   run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: app_test

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GCE
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_HOST}}
          username: ${{ secrets.GCE_USER}}
          key: ${{ secrets.GCE_PRIVATE_KEY}}
          port: 22
          script: |
            ssh -vvv -i "$SSH_PRIVATE_KEY" ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} "echo Hello"
            cd /var/www/html
            git pull origin main
            composer update
            composer install --no-interaction --no-dev --optimize-autoloader
            php artisan migrate --seed
